export CUDA_VISIBLE_DEVICES=0,1,2,3
export PYTHONUTF8=1
NUM_GPUS=$(echo $CUDA_VISIBLE_DEVICES | awk -F',' '{print NF}')

set -x
export WANDB_API_KEY="Your Wandb Key"
export WANDB_MODE=offline
export ACCELERATE_LOG_LEVEL=info
export HYDRA_FULL_ERROR=1
LLM_PATH="Your LLM Path"

PROJ_NAME="DAPO_Dataset"
alpha_start=0.01
alpha_end=1e-5
interval=1
total_epochs=3
EXP_NAME="Your Exp Name"
train_files=data/dapo/train_original.parquet
train_aug_files=data/dapo/train_rewrite_Qwen3-32B.parquet
lr=3e-6

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=co_rewarding_grpo \
    data.use_aug=True \
    data.train_files=$train_files \
    data.train_aug_files=$train_aug_files \
    data.val_files=data/math/test.parquet \
    data.train_batch_size=128 \
    data.max_prompt_length=512 \
    data.max_response_length=3072 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=$LLM_PATH \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.model.use_fused_kernels=False \
    actor_rollout_ref.actor.optim.lr=$lr \
    actor_rollout_ref.actor.optim.warmup_style=cosine \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.1 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.sliding_average.enable=True \
    actor_rollout_ref.ref.sliding_average.update_interval=$interval \
    actor_rollout_ref.ref.sliding_average.alpha_start=$alpha_start \
    actor_rollout_ref.ref.sliding_average.alpha_end=$alpha_end \
    algorithm.use_kl_in_reward=False \
    reward_model.reward_manager=co_rewarding_III \
    reward_model.val_reward_manager=naive \
    trainer.critic_warmup=0 \
    trainer.val_before_train=True \
    trainer.rollout_data_dir=rollout_log/${EXP_NAME}_ori/policy \
    trainer.ref_rollout_data_dir=rollout_log/${EXP_NAME}_ori/ref \
    trainer.rollout_data_dir_aug=rollout_log/${EXP_NAME}_aug/policy \
    trainer.ref_rollout_data_dir_aug=rollout_log/${EXP_NAME}_aug/ref \
    trainer.n_gpus_per_node=$NUM_GPUS \
    trainer.nnodes=1 \
    trainer.logger=['console','wandb'] \
    trainer.project_name=$PROJ_NAME \
    trainer.experiment_name=$EXP_NAME \
    trainer.save_freq=30 \
    trainer.test_freq=10 \
    trainer.total_epochs=3 2>&1 | tee wandb/$EXP_NAME.log
